In [7]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as pathces
from PIL import Image
%matplotlib inline

In [27]:
Sample_raw_x = 32
Sample_raw_y = 32

rpn_stride = 8

Feature_size_X = Sample_raw_x/rpn_stride
Feature_size_Y = Sample_raw_y/rpn_stride

scales = [1,2,4]
ratios =[0.5,1,2] 

In [28]:
fx = np.arange(Feature_size_X)
fy = np.arange(Feature_size_Y)

In [29]:
FX,FY = np.meshgrid(fx,fy)

In [30]:
FX.flatten()

array([0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.])

In [31]:
FY.flatten()

array([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [32]:
scales,ratios = np.meshgrid(scales,ratios)

In [34]:
ratios.flatten()

array([0.5, 0.5, 0.5, 1. , 1. , 1. , 2. , 2. , 2. ])

In [36]:
scale =4
ratio = 2
x=scale * np.sqrt(ratio)
y=scale / np.sqrt(ratio)


5.656854249492381